/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Acceso_A_Datos.CitaVacunaData;
import Acceso_A_Datos.VacunaData;
import Entidades.CitaVacunacion;
import Entidades.Vacuna;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author familia maida
 */
public class centroVacunacion extends javax.swing.JFrame {
private DefaultTableModel modeloT =new DefaultTableModel(){   
     
    @Override
    public boolean isCellEditable(int f, int c) {
        return false;
 }
 };
     DefaultListModel modelo =  new DefaultListModel();
     
    public centroVacunacion() {
        initComponents();
        listaVacunatorios();
        armarCabecera();
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTablaAplicadas = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlListaCentrosAplicados = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jBanerLogoVacunar = new javax.swing.JLabel();
        jBannerVacuna = new javax.swing.JLabel();
        jX = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtTablaAplicadas.setBackground(new java.awt.Color(255, 255, 255));
        jtTablaAplicadas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtTablaAplicadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "vacuna", "NroDeSerie", "DniPaciente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTablaAplicadas.setGridColor(new java.awt.Color(180, 0, 0));
        jtTablaAplicadas.setSelectionBackground(new java.awt.Color(180, 0, 0));
        jtTablaAplicadas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jtTablaAplicadas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtTablaAplicadas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 602, 130));

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jlListaCentrosAplicados.setBackground(new java.awt.Color(255, 255, 255));
        jlListaCentrosAplicados.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(180, 0, 0)));
        jlListaCentrosAplicados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlListaCentrosAplicados.setSelectionBackground(new java.awt.Color(180, 0, 0));
        jlListaCentrosAplicados.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jlListaCentrosAplicados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlListaCentrosAplicadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlListaCentrosAplicados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 110));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(180, 0, 0));
        jLabel2.setText("*Seleccione un vacunatorio para ver detalle");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jBanerLogoVacunar.setBackground(new java.awt.Color(180, 0, 0));
        jBanerLogoVacunar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/Vacunar-Logo-45.png"))); // NOI18N
        jBanerLogoVacunar.setOpaque(true);
        jPanel1.add(jBanerLogoVacunar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jBannerVacuna.setBackground(new java.awt.Color(180, 0, 0));
        jBannerVacuna.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jBannerVacuna.setForeground(new java.awt.Color(255, 255, 255));
        jBannerVacuna.setText(" Centros de Vacunacion");
        jBannerVacuna.setOpaque(true);
        jPanel1.add(jBannerVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 780, 50));

        jX.setBackground(new java.awt.Color(180, 0, 0));
        jX.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jX.setForeground(new java.awt.Color(255, 255, 255));
        jX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jX.setText("X");
        jX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jX.setOpaque(true);
        jX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jXMouseExited(evt);
            }
        });
        jPanel1.add(jX, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/Vacunar-Logotipo-2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlListaCentrosAplicadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlListaCentrosAplicadosValueChanged
        if (!evt.getValueIsAdjusting()) {
        iniciaTabla(); // Llama a tu método para llenar la tabla cuando se selecciona un centro
    }
    }//GEN-LAST:event_jlListaCentrosAplicadosValueChanged

    private void jXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXMouseClicked

        // Boton Cerrar
        this.dispose();
    }//GEN-LAST:event_jXMouseClicked

    private void jXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXMouseEntered
        // Efecto de posicion
        jX.setBackground(Color.white);
        jX.setForeground(new Color(180, 0, 0));

    }//GEN-LAST:event_jXMouseEntered

    private void jXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXMouseExited
        // Tremarcado de boton X
        jX.setBackground(new Color(180, 0, 0));
        jX.setForeground(Color.WHITE);

    }//GEN-LAST:event_jXMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(centroVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(centroVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(centroVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(centroVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new centroVacunacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBanerLogoVacunar;
    private javax.swing.JLabel jBannerVacuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jX;
    private javax.swing.JList<CitaVacunacion> jlListaCentrosAplicados;
    private javax.swing.JTable jtTablaAplicadas;
    // End of variables declaration//GEN-END:variables
private void listaVacunatorios() {
    CitaVacunaData citaData = new CitaVacunaData();
    List<CitaVacunacion> citas = citaData.listaCentroCitaVacunacion();
    
    DefaultListModel<CitaVacunacion> modelo = new DefaultListModel<>();

    for (CitaVacunacion citaVacunacion : citas) {
        modelo.addElement(citaVacunacion);
    }

    jlListaCentrosAplicados.setModel(modelo);
}
private void armarCabecera() {
        modeloT.addColumn("Vacuna");
        modeloT.addColumn("NroSerie");
        modeloT.addColumn("DniPaciente");
        
        jtTablaAplicadas.setModel(modeloT);
         jtTablaAplicadas.setDefaultEditor(Object.class, null);
       
    }
private void iniciaTabla() {
    ------------------------------------------------------------------CitaVacunaData citaData = new CitaVacunaData();
    CitaVacunacion centroSeleccionado = jlListaCentrosAplicados.getSelectedValue();
    
    if (centroSeleccionado != null) {
        // Obtén el nombre del centro seleccionado
        String centroSeleccionadoNombre = centroSeleccionado.getCentroVacuna();

        // Obten las dosis aplicadas en el centro seleccionado
        List<CitaVacunacion> aplicadas = citaData.listaAplicadasCitaVacunacion(centroSeleccionadoNombre, true);

        modeloT.setRowCount(0); // Limpia las filas existentes en la tabla
        for (CitaVacunacion aplicada : aplicadas) {
            modeloT.addRow(new Object[]{ aplicada.getVacuna().getMarca(), aplicada.getVacuna().getNumSerie(), aplicada.getCiudadano().getDni()});
        }
    }
    jtTablaAplicadas.setModel(modeloT);
}

    void moveToFront() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


}

